
SELECT *
FROM EMPLOYEES; 

SELECT MAX(SALARY), DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT * 
FROM EMPLOYEES
WHERE DEPARTMENT_ID=10;

SELECT * 
FROM EMPLOYEES
WHERE DEPARTMENT_ID=20;

SELECT AVG(SALARY), DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT  DEPARTMENT_ID, MAX(SALARY) 
FROM EMPLOYEES
WHERE  DEPARTMENT_ID != 20
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY)>5000;

SELECT  DEPARTMENT_ID, MAX(SALARY) AS SAL
FROM EMPLOYEES
WHERE  DEPARTMENT_ID != 20
GROUP BY DEPARTMENT_ID
HAVING SAL>5000;


