-- 182 Write your MySQL query statement below
SELECT EMAIL
FROM PERSON
GROUP BY EMAIL
HAVING COUNT(EMAIL)>1



-- 181 Write your MySQL query statement below
SELECT EMP.NAME AS EMPLOYEE
FROM EMPLOYEE AS EMP, EMPLOYEE AS MGR
WHERE EMP.MANAGERID = MGR.ID AND EMP.SALARY > MGR.SALARY



-- 183