-- Join whithout use JOIN keyword
USE DUMMYDB;

SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES,
	DEPARTMENTS
WHERE
	EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- Join using JOIN keyword
SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES
	JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES
	JOIN DEPARTMENTS USING(DEPARTMENT_ID);

SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES
	INNER JOIN DEPARTMENTS USING(DEPARTMENT_ID);

SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES
	LEFT JOIN DEPARTMENTS USING(DEPARTMENT_ID);

SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES
	RIGHT JOIN DEPARTMENTS USING(DEPARTMENT_ID);

SELECT
	EMPLOYEES.FIRST_NAME,
	DEPARTMENTS.DEPARTMENT_NAME
FROM
	EMPLOYEES
	CROSS JOIN DEPARTMENTS USING(DEPARTMENT_ID);

-- self join
SELECT
	E.FIRST_NAME,
	M.FIRST_NAME
FROM
	EMPLOYEES AS e
	JOIN EMPLOYEES AS m ON e.EMPLOYEE_ID = m.MANAGER_ID;