CREATE TABLE Employees (
    Employee_Id INT PRIMARY KEY,
    First_Name VARCHAR(50),
    Last_Name VARCHAR(50),
    Date_of_Birth DATE,
    Department_Id INT,
    Salary DECIMAL(10, 2)
);

CREATE TABLE Projects (
    Project_ID INT PRIMARY KEY,
    Project_Name VARCHAR(100),
    Start_Date DATE,
    End_Date DATE,
    Budget DECIMAL(15, 2)
);

CREATE TABLE Employee_Projects (
    Employee_ID INT,
    Project_ID INT,
    PRIMARY KEY (Employee_ID, Project_ID),
    FOREIGN KEY (Employee_ID) REFERENCES Employees(Employee_Id),
    FOREIGN KEY (Project_ID) REFERENCES Projects(Project_ID)
);

-- INNER JOIN
SELECT
    E.FIRST_NAME,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES E
    INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- LEFT JOIN
SELECT
    E.FIRST_NAME,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES E
    LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- RIGHT JOIN
SELECT
    E.FIRST_NAME,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES E
    RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- CROSS JOIN
SELECT
    E.FIRST_NAME,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES E
    CROSS JOIN DEPARTMENTS D;